export class PositionComponent {
    constructor(x, y) {
        this.x = x || 0;
        this.y = y || 0;
    }
}

export class VelocityComponent {
    constructor(vx, vy) {
        this.vx = vx || 0;
        this.vy = vy || 0;
    }
}

export class WordComponent {
    constructor(word) {
        this.word = word;
        this.originalWord = word;
    }
}

export class RenderComponent {
    constructor(type, chibiFile) {
        this.type = type; // 'normal', 'boss', 'story'
        this.chibiFile = chibiFile;
        this.el = null; // DOM element reference
        this.lane = 0;
    }
}

export class LaneComponent {
    constructor(lane) {
        this.lane = lane;
    }
}

// --- KINETIC RESONANCE COMPONENTS ---

export class PhysicsComponent {
    constructor(mass = 1, friction = 0.95) {
        this.mass = mass;
        this.friction = friction;
        this.vx = 0;
        this.vy = 0;
        this.ax = 0; // Acceleration
        this.ay = 0;
    }
}

export class RopeComponent {
    constructor(startX, startY, length = 100, segments = 5) {
        this.length = length;
        this.segments = segments;
        // The actual physics points will be generated by the PhysicsSystem
        this.rope = null;
        this.anchorEntityId = null; // If attached to something moving (like a ship)
    }
}
